version: '3.8'

services:
  db:
    image: postgres:15
    container_name: vocational_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: vocational_backend
    environment:
      POSTGRES_SERVER: ${POSTGRES_SERVER}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      SECRET_KEY: ${SECRET_KEY}
    ports:
      - "8098:8000"
    depends_on:
      - db
    volumes:
      - .:/app
      - ./app/ml/assets:/app/app/ml/assets
      - ./app/ml/datasets:/app/app/ml/datasets

volumes:
  postgres_data:
